//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projeto_Laboral.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class db_prolaboreEntities : DbContext
    {
        public db_prolaboreEntities()
            : base("name=db_prolaboreEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<exib_client> exib_client { get; set; }
        public DbSet<exib_gallery> exib_gallery { get; set; }
        public DbSet<exibition_atv> exibition_atv { get; set; }
        public DbSet<exibition_home> exibition_home { get; set; }
        public DbSet<exibition_prf> exibition_prf { get; set; }
    }
}
