//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projeto_Laboral.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class exibition_home
    {
        public int id { get; set; }
        public int user { get; set; }
        public string img_home { get; set; }
        public string sobre { get; set; }
        public string titulo { get; set; }
        public string text { get; set; }
        public string titulo2 { get; set; }
        public string text2 { get; set; }
        public string titulo3 { get; set; }
        public string text3 { get; set; }
        public System.TimeSpan hora { get; set; }
        public System.DateTime data { get; set; }
    }
}
