//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projeto_Laboral.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class exib_gallery
    {
        public int id { get; set; }
        public string title { get; set; }
        public string text { get; set; }
        public int type { get; set; }
        public string img { get; set; }
        public string video { get; set; }
        public Nullable<System.DateTime> data { get; set; }
    }
}
