//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projeto_Laboral.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class exibition_atv
    {
        public int id { get; set; }
        public string user { get; set; }
        public string img_serv { get; set; }
        public string text { get; set; }
        public Nullable<System.TimeSpan> hora { get; set; }
        public Nullable<System.DateTime> data { get; set; }
    }
}
