//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cadastro_usuario
    {
        public long id_user { get; set; }
        public string nome { get; set; }
        public string tp_user { get; set; }
        public int id_setor { get; set; }
        public string email { get; set; }
        public string telefone { get; set; }
        public string senha { get; set; }
        public Nullable<int> online { get; set; }
        public System.DateTime data { get; set; }
    }
}
