//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cadastro_lugar
    {
        public long id_moradia { get; set; }
        public string lugar_posicionamento { get; set; }
        public string inquilino { get; set; }
        public string email { get; set; }
        public System.DateTime data { get; set; }
    }
}
