//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class d_bordo_s1
    {
        public long ln { get; set; }
        public long protocolo { get; set; }
        public int id_lugar { get; set; }
        public long id_user { get; set; }
        public string t_problema { get; set; }
        public string problema { get; set; }
        public long user_at { get; set; }
        public System.DateTime dt_at { get; set; }
        public System.DateTime data { get; set; }
    }
}
